apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ardurbot-computers
  namespace: ardurbot
rules:
  - apiGroups: [""]
    resources: [pods, persistentvolumeclaims]
    verbs: [get, create, delete]
  - apiGroups: [""]
    resources: [pods/exec]
    verbs: [get, create]
