/**
 * The lexicons of the classifier, and nothing else. One list per signal; a list may mix
 * languages freely. Latin needles are matched on word boundaries with an optional plural
 * suffix; CJK needles are matched as substrings. Everything else in the effort router
 * reads structure, which survives translation.
 */
export const WORD_LISTS = {
  greeting: [
    "hi",
    "hey",
    "hello",
    "yo",
    "sup",
    "gm",
    "morning",
    "bonjour",
    "salut",
    "hola",
    "ciao",
    "hallo",
    "привет",
    "你好",
    "こんにちは",
    "안녕",
    "नमस्ते",
    "नमस्कार",
    "हैलो",
    "مرحبا",
    "أهلا",
  ],
  greetingPhrase: [
    "how are you",
    "how's it going",
    "how are things",
    "ça va",
    "comment ça va",
    "qué tal",
    "cómo estás",
    "wie geht",
    "wie geht's",
    "как дела",
    "как ты",
    "元気ですか",
    "잘 지내",
    "कैसे हैं",
    "कैसे हो",
    "क्या हाल",
    "كيف حالك",
    "كيف الحال",
  ],
  farewell: [
    "bye",
    "goodbye",
    "cya",
    "later",
    "thanks",
    "thank",
    "thx",
    "ty",
    "merci",
    "gracias",
    "danke",
    "спасибо",
    "谢谢",
    "ありがとう",
    "धन्यवाद",
    "شكرا",
  ],
  filler: [
    "lol",
    "haha",
    "nice",
    "cool",
    "great",
    "ok",
    "okay",
    "wow",
    "lmao",
    "jaja",
    "done",
    "well done",
    "good job",
    "great work",
    "nicely done",
    "哈哈",
  ],
  questionWord: [
    "what",
    "when",
    "where",
    "who",
    "why",
    "how",
    "which",
    "does",
    "is",
    "are",
    "can",
    "could",
    "should",
    "qué",
    "cómo",
    "dónde",
    "cuándo",
    "quién",
    "cuál",
    "was",
    "wer",
    "wo",
    "wann",
    "quoi",
    "comment",
    "où",
    "qui",
    "почему",
    "что",
    "как",
    "什么",
    "怎么",
    "几",
    "何",
    "なに",
    "どう",
  ],
  /** Failure vocabulary: an error report, a crashed or failed state, an outage word. */
  debugWord: [
    "error",
    "errors",
    "bug",
    "fails",
    "failing",
    "failed",
    "fail",
    "throw",
    "throws",
    "threw",
    "crash",
    "crashes",
    "crashed",
    "exception",
    "traceback",
    "panic",
    "stack",
    "segfault",
    "undefined",
    "down",
    "outage",
    "timed out",
    "times out",
    "timing out",
    "timeout error",
    "hung",
    "hang",
    "hangs",
    "freeze",
    "freezes",
    "frozen",
    "froze",
    "stuck",
    "deadlock",
    "leak",
    "stale",
    "lag",
    "lagging",
    "spike",
    "spiked",
    "backed up",
    "stopped",
    "broke",
    "broken",
    "empty results",
    "no results",
    "fehler",
    "fehlgeschlagen",
    "abgestürzt",
    "stirbt",
    "kaputt",
    "erreur",
    "erro",
    "falló",
    "fallo",
    "falla",
    "fallando",
    "fallido",
    "no funciona",
    "roto",
    "planté",
    "plante",
    "en panne",
    "bloquée",
    "s'arrête",
    "fallito",
    "non funziona",
    "క్రాష్",
    "panne",
    "ошибка",
    "не работает",
    "падает",
    "ошибки",
    "错误",
    "报错",
    "失败",
    "崩溃",
    "挂了",
    "落ちる",
    "エラー",
    "バグ",
  ],
  fix: [
    "fix",
    "fixes",
    "fixing",
    "repair",
    "regression",
    "repro",
    "reproduce",
    "behebe",
    "reparieren",
    "réparer",
    "arreglar",
    "исправь",
    "修复",
    "修一下",
    "修正",
    "直して",
    "고쳐",
  ],
  /** Where evidence lives: named in a failure report, weak support for debugging. */
  evidence: [
    "logs",
    "log",
    "logcat",
    "trace",
    "metrics",
    "monitoring",
    "telemetry",
    "日志",
    "లాగ్స్",
    "ログ",
  ],
  /** Named system components. Naming one is not an ask to run it; it anchors ops and debug. */
  infra: [
    "prod",
    "production",
    "staging",
    "canary",
    "cluster",
    "node",
    "pod",
    "pods",
    "container",
    "queue",
    "worker",
    "workers",
    "jobs",
    "database",
    "db",
    "postgres",
    "mysql",
    "redis",
    "kafka",
    "rabbitmq",
    "elasticsearch",
    "prometheus",
    "grafana",
    "kubernetes",
    "k8s",
    "namespace",
    "ingress",
    "controller",
    "gateway",
    "proxy",
    "load balancer",
    "cache",
    "certificate",
    "cert",
    "certs",
    "tls",
    "ssl",
    "dns",
    "service",
    "server",
    "instance",
    "replica",
    "replicas",
    "deployment",
    "rollout",
    "cron",
    "backup",
    "region",
    "zone",
    "environment",
    "exporter",
    "dashboard",
    "pipeline",
    "index",
    "shard",
    "broker",
    "topic",
    "consumer",
    "volume",
    "persistent volume",
    "connection pool",
    "timeout",
    "default",
    "release",
    "keys",
    "bucket",
    "buckets",
    "file d'attente",
    "服务",
    "数据库",
    "队列",
    "集群",
    "数据库",
    "ステージング",
    "データベース",
    "キュー",
  ],
  /** Verbs that ask for the system to be run or changed: operations work. */
  opsVerb: [
    "deploy",
    "redeploy",
    "restart",
    "reboot",
    "roll out",
    "roll back",
    "scale",
    "provision",
    "rotate",
    "renew",
    "back up",
    "restore",
    "fail over",
    "drain",
    "cordon",
    "pause",
    "resume",
    "enable",
    "disable",
    "raise",
    "lower",
    "bump",
    "increase",
    "decrease",
    "tune",
    "adjust",
    "set up",
    "expand",
    "ship",
    "backup",
    "take a backup",
    "take a snapshot",
    "snapshot",
    "whitelist",
    "unblock",
    "retire",
    "decommission",
    "set",
    "turn on",
    "turn off",
    "switch on",
    "switch off",
    "sube",
    "reinicia",
    "activa",
    "riprova",
    "搭建",
    "备份",
    "deployen",
    "déployer",
    "desplegar",
    "部署",
    "上线",
    "重启",
    "再起動",
    "运维",
    "배포",
  ],
  /** "fix it", "retry it": the object is a pronoun, so the ask is remediation of a live issue. */
  remediationPhrase: ["fix it", "fix this", "patch it", "retry it", "restart it", "roll it back"],
  codeChangeVerb: [
    "refactor",
    "implement",
    "rename",
    "extract",
    "optimize",
    "optimise",
    "migrate",
    "port",
    "wire",
    "remove",
    "delete",
    "update",
    "move",
    "change",
    "split",
    "decouple",
    "重命名",
    "重构",
    "实现",
    "実装",
    "리팩터링",
  ],
  createVerb: [
    "write",
    "create",
    "build",
    "add",
    "make",
    "generate",
    "schreibe",
    "erstelle",
    "créer",
    "crear",
    "写",
    "创建",
    "新增",
    "作成",
    "生成",
    "만들어",
  ],
  /** Objects that are code or configuration. Writing one is a code change. */
  codeArtifact: [
    "button",
    "endpoint",
    "api",
    "test",
    "tests",
    "hook",
    "route",
    "migration",
    "schema",
    "interface",
    "class",
    "method",
    "page",
    "form",
    "modal",
    "flag",
    "config",
    "module",
    "middleware",
    "query",
    "helper",
    "handler",
    "provider",
    "component",
    "function",
    "library",
    "package",
    "dependency",
    "dockerfile",
    "makefile",
    "circuit breaker",
    "code",
    "probe",
    "retry",
    "代码",
    "函数",
    "按钮",
    "接口",
    "页面",
  ],
  /** Objects that are prose. Writing one is writing. */
  proseArtifact: [
    "haiku",
    "poem",
    "essay",
    "blog post",
    "blog",
    "tweet",
    "caption",
    "story",
    "limerick",
    "letter",
    "email",
    "note",
    "notes",
    "paragraph",
    "intro",
    "copy",
    "blurb",
    "announcement",
    "headline",
    "subject line",
    "runbook",
    "postmortem",
    "apology",
    "gedicht",
    "verse",
    "公告",
    "邮件",
    "文章",
  ],
  reviewVerb: [
    "review",
    "feedback",
    "critique",
    "lgtm",
    "look over",
    "look at",
    "take a look",
    "good to merge",
    "ready to merge",
    "ship it",
    "revisión",
    "revisar",
    "评审",
    "审一下",
    "看一下",
    "看看",
    "レビュー",
    "리뷰",
  ],
  reviewObject: ["pr", "diff", "patch", "pull request", "mr", "changeset"],
  planWord: [
    "plan",
    "roadmap",
    "strategy",
    "milestone",
    "milestones",
    "architecture",
    "architect",
    "design",
    "decompose",
    "break down",
    "breakdown",
    "structure",
    "outline",
    "strukturieren",
    "planifier",
    "planung",
    "planear",
    "計画",
    "计划",
    "规划",
    "方案",
    "設計",
    "계획",
  ],
  researchWord: [
    "research",
    "investigate",
    "compare",
    "survey",
    "literature",
    "paper",
    "papers",
    "arxiv",
    "benchmark",
    "sota",
    "state of the art",
    "find out",
    "dig into",
    "rechercher",
    "untersuchen",
    "forschung",
    "investigar",
    "研究",
    "调研",
    "调查",
    "調査",
    "연구",
  ],
  summaryWord: [
    "summarize",
    "summarise",
    "summary",
    "tldr",
    "tl;dr",
    "recap",
    "digest",
    "condense",
    "key points",
    "main points",
    "short version",
    "résume",
    "resumen",
    "resumir",
    "zusammen",
    "总结",
    "摘要",
    "概括",
    "要約",
    "요약",
  ],
  writingVerb: [
    "draft",
    "rewrite",
    "reword",
    "polish",
    "translate",
    "translation",
    "proofread",
    "rephrase",
    "compose",
    "écrire",
    "écris",
    "rédige",
    "escribir",
    "翻译",
    "润色",
    "書く",
    "번역",
    "작성",
  ],
  dataVerb: [
    "analyze",
    "analyse",
    "plot",
    "chart",
    "pivot",
    "dedupe",
    "group",
    "rank",
    "count",
    "analysiere",
    "analysieren",
    "grow",
    "grew",
    "growth",
    "drop",
    "dropped",
    "rise",
    "risen",
    "rose",
    "decline",
    "declined",
    "分析",
    "统计",
    "图表",
  ],
  dataNoun: [
    "csv",
    "excel",
    "spreadsheet",
    "spreadsheets",
    "sql",
    "dataset",
    "dataframe",
    "average",
    "median",
    "percentile",
    "p95",
    "p99",
    "statistics",
    "stats",
    "correlation",
    "latency",
    "latencies",
    "throughput",
    "uptime",
    "queue depth",
    "cohort",
    "daten",
    "错误率",
    "数据",
    "データ",
    "분석",
  ],
  /** Question shapes that ask for a count or a magnitude: the data reading of a question. */
  quantityPhrase: [
    "how many",
    "how much",
    "how often",
    "what percentage",
    "what fraction",
    "combien",
    "wie viele",
    "wie viel",
    "cuántos",
    "cuántas",
    "cuanto",
    "cuanta",
    "сколько",
    "几个",
    "多少",
    "most",
    "fewest",
    "least",
    "longer than",
    "more than",
    "fewer than",
    "compared to",
    "versus",
    "vs",
  ],
  /** A period to aggregate or compare over: the data reading of a time range. */
  temporalScope: [
    "yesterday",
    "last week",
    "last month",
    "last quarter",
    "last night",
    "last year",
    "this morning",
    "this week",
    "this month",
    "this quarter",
    "today",
    "over the past",
    "in the last",
    "ayer",
    "hier",
    "вчера",
    "letzte Woche",
    "letzte Nacht",
    "letzte Monat",
    "diese Woche",
    "per day",
    "per week",
    "each night",
    "every night",
    "each day",
    "every day",
    "chaque nuit",
    "chaque jour",
    "jede Nacht",
    "每天",
    "每晚",
    "昨天",
    "昨日",
  ],
} as const;

export type WordListName = keyof typeof WORD_LISTS;
